name: Multiple Jobs Workflow

on:
  pull_request:
    branches:
      - mainone
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm test
  
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm run build
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]  # Wait for both test and build to succeed
    steps:
      - run: ./deploy.sh
